name: Run frontend scripts

"on": push

jobs:
 lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - name: npm install
        run: cd frontend && npm install
      - name: lint
        run: cd frontend && npm run lint-css
      - name: test
        run: cd frontend && npm run test:unit
      - name: Build
        run: cd frontend && npm run build
